// <auto-generated />
using Duello.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Duello.Migrations
{
    [DbContext(typeof(BudgetDatabase))]
    [Migration("20210428170442_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Duello.Budget", b =>
                {
                    b.Property<double>("JumlahUang")
                        .HasColumnType("float");

                    b.Property<string>("NamaBudget")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Duello.Expense", b =>
                {
                    b.Property<double>("JumlahUang")
                        .HasColumnType("float");

                    b.Property<string>("NamaBudget")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Duello.Income", b =>
                {
                    b.Property<double>("JumlahUang")
                        .HasColumnType("float");

                    b.Property<string>("NamaBudget")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
